
WIDTH = 480
HEIGHT = 480

TYPE_SPRITE = 0
TYPE_BULLET = 1
TYPE_CANNONBALL = 2
TYPE_ALPHA = 3
TYPE_LAMBDA = 4
TYPE_OBSTACLE = 5

TURRET_MONO = 0
TURRET_SOLI = 1
TURRET_DUO = 2
TURRET_OMNI = 3
TURRET_WIDER = 4
TURRET_BECKY = 5

MSGID_REGISTER = 1
MSGID_REGISTER_ACK = 2
MSGID_UPDATE = 3
MSGID_ACTION = 4

ACTID_MOTOR_ON = 1
ACTID_MOTOR_OFF = 2
ACTID_REVERSE_ON = 3
ACTID_REVERSE_OFF = 4
ACTID_FIRE_ON = 5
ACTID_FIRE_OFF = 6
ACTID_ROTATE_CL = 7
ACTID_ROTATE_CC = 8
ACTID_ROTATE_STOP = 9

STATUS_NOK = 0
STATUS_OK = 1

MESSAGE_TIME = 20 # ms
RESPAWN_TIME = 5000 # ms
